
- name: Install Git
  become: true
  apt:
    name: git
    state: present
    update_cache: yes
  
- name: Install Python and pip
  become: true
  apt:
    state: present
    update_cache: yes
    name:
      - python3
      - python3-pip
      - python3-setuptools

- name: Install UFW
  become: true
  apt:
    state: present
    name: 
      - ufw